### ISSUE TITLE
Wrong polarization equation?

### ISSUE THREAD

**Issue by wfarah** [luigifcruz/blade#49]
I'm not sure about here, but I think we might be missing a `1j` as there's a 90deg phase shift to synthesize circular. 
The equation should be:
```
R = X + 1j*Y
L = X - 1j*Y
```
https://github.com/luigifcruz/blade/blob/main/src/modules/polarizer/polarizer.cu#L12-L13

**Comment by wfarah** [comment]
I see it's wrong in the python tests too
https://github.com/luigifcruz/blade/blob/main/tests/modules/polarizer/polarizer.py#L64-L65

**Comment by luigifcruz** [comment]
Yup, this does make sense. I'll patch this tomorrow.

![](https://www.qsl.net/s/sv1bsx/antenna-pol/cw_ccw-dipoles.gif)
